<?php include("header.html") ?>

     
<div id='site_content'>

<h2>Gallery</h2>

<div class='myGallery'>
     
  <dl class='gallery-item-large'>
    <dt>
   <a href='http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7862284'><img height="180"  src="images/gallery/Brain_Image_volume.png" class="attachment-thumbnail" alt="" /> <img height="180"  src="images/gallery/Brain_RORPO_volume.png" class="attachment-thumbnail" alt="" /> <img height="180"  src="images/gallery/RORP0_plan_spiral_blob_iso.png" class="attachment-thumbnail" alt="" />

<img height="180"  src="images/gallery/RORPO_plan_spiral_blob_RORPO_30_1-7_3_iso.png" class="attachment-thumbnail" alt="" /></a>

   </dt>
    <dd class='gallery-reference'>
     O. Merveille, H. Talbot, L. Najman, N. Passat.  Curvilinear structure analysis by ranking the orientation responses of path operators. IEEE Tr      ansactions on Pattern Analysis and Machine Intelligence 40(2):304-317 (2018).	      
    </dd>
  </dl><br style="clear: both">



  <dl class='gallery-item'>  
     <dt>
    <a href='https://www.lrde.epita.fr/dload/papers/carlinet.15.itip.pdf'><img  height="250" src="images/gallery/MToS.png" class="attachment-thumbnail" alt="" /></a>     
    </dt>
    <dd class='gallery-reference'>
    Edwin Carlinet and Thierry Géraud. {MToS}: A Tree of Shapes for Multivariate Images. IEEE Transactions on Image Processing, 24(12):53330--5343    (2015).	      
    </dd>
  </dl>

  <dl class='gallery-item'>  
    <dt>
      <a href='http://www.sciencedirect.com/science/article/pii/S1077314212001786'><img width="250" height="250" src="images/gallery/2013/TS.png" class="attachment-thumbnail" alt="" /></a>
    </dt>
    <dd class='gallery-reference'>
     P. Ngo, Y. Kenmochi, N. Passat, H. Talbot. Combinatorial
      structure of rigid transformations in 2D digital
      images. Computer Vision and Image Understanding, 117(4):393-408
      (2013).     
    </dd>
    <dd class='gallery-caption'>
      Parameter space of 2-dimensional continuous rigid transformations (a<sub>1</sub>,
      a<sub>2</sub>: translation; &theta;: rotation), subdivided with into cells that
      represent the associated discrete rigid transformations. The visualized
      surfaces correspond to limit cases at the frontier between to pixels.
    </dd>
  </dl><br style="clear: both">
      
  <dl class='gallery-item-large'>
    <dt>
      <a href='http://www.sciencedirect.com/science/article/pii/S0166218X13002771'><img  height="250"
	src="images/gallery/2013/sphereRoussillonToutant2013.jpg"/></a>
    </dt>
    <dd class='gallery-reference'>
      J.-L. Toutant, E. Andres, T. Roussillon, Digital circles,
      spheres and hyperspheres: From morphological models to analytical
      characterizations and topological properties, Discrete Applied
      Mathematics, Volume 161, Issues 16–17, November 2013, Pages 2662-2677
    </dd>
    <dd class='gallery-caption'>
    </dd>
  </dl><br style="clear: both">

  <dl class='gallery-item'>
    <dt>
      <a href='http://www.sciencedirect.com/science/article/pii/S1077314214001003'><img  height="250" src="images/gallery/2013/xyz512.png"/></a>
    </dt>
    <dd class='gallery-reference'>
      D. Coeurjolly, J.-O. Lachaud, J. Levallois, Multigrid convergent
      principal curvature estimators in digital geometry, Computer
      Vision and Image Understanding, 2014.
    </dd>
  </dl>

    <dl class='gallery-item'>
    <dt>
      <a href=''><img  height="250" src="images/gallery/2013/textureDigitalSurface.jpg"/></a>
    </dt>
    <dd class='gallery-reference'>
      C. Cartade, C. Mercat, R. Malgouyres, C. Samir,
      Mesh Parameterization with Generalized Discrete Conformal Maps, Journal of Mathematical Imaging and Vision, May 2013, Volume 46, Issue 1, pp 1-11 
    </dd>
  </dl>
    
</div>


<!-- <div id='gallery-1' class='gallery galleryid-41 gallery-columns-2> -->
<!--      gallery-size-thumbnail'>> -->

<!--   <dl class='gallery-item'>> -->
    
<!--    <dt class='gallery-icon landscape'>> -->
<!--      <a href='http://link.springer.com/article/10.1007%2Fs10851-013-0474-z'><img width="250" height="250" src="images/gallery/2013/retina_regular_anim.gif" class="attachment-thumbnail" alt="" /></a>> -->
<!--       </dt>> -->
<!--    <dd class='wp-caption-text gallery-caption'>> -->
<!--      <font color="#09BCE8">P. Ngo, Y. Kenmochi, N. Passat, H. Talbot. Combinatorial> -->
<!--        structure of rigid transformations in 2D digital> -->
<!--        images. Computer Vision and Image Understanding, 117(4):393-408> -->
<!--        (2013). <br> </font>> -->
     
<!--      Binary object obtained from retina image segmentation. The> -->
<!--      non-processed image suffers from topological alterations during> -->
<!-- 	rotation, due to the small size of linear structures. The> -->
<!-- 	"regularized" image, generated by a sup/inf Khalimsky grid> -->
<!-- 	embedding, is no longer affected by topological changes.> -->
<!--     </dd></dl>> -->
<!--   <dl class='gallery-item'>> -->
      
<!--     <dt class='gallery-icon landscape'>> -->
<!--       <a href='http://www.sciencedirect.com/science/article/pii/S1077314212001786'><img width="250" height="250" src="images/gallery/2013/TS.png" class="attachment-thumbnail" alt="" /></a>> -->
<!--     </dt>> -->
<!--     <dd class='wp-caption-text gallery-caption'>> -->
<!--       <font color="#09BCE8">P. Ngo, N. Passat, Y. Kenmochi, H. Talbot. Topology-preserving> -->
<!--       rigid transformation of 2D digital images. IEEE Transactions on> -->
<!--       Image Processing, 23(2):885-897 (2014).<br></font>> -->
      
<!--       Parameter space of 2-dimensional continuous rigid transformations (a1,> -->
<!--       a2: translation; theta: rotation), subdivided with into cells that> -->
<!--       represent the associated discrete rigid transformations. The visualized> -->
<!--       surfaces correspond to limit cases at the frontier between to pixels.> -->
<!--   </dd></dl><br style="clear: both" />> -->
  
<!--   <dl class='gallery-item'>> -->
    
<!--     <dt class='gallery-icon landscape' >> -->
<!--       <a href='http://www.sciencedirect.com/science/article/pii/S0166218X13002771'><img  height="250"> -->
<!--       src="images/gallery/2013/sphereRoussillonToutant2013.jpg"> -->
<!--       class="attachment-thumbnail" alt="" /></a>> -->
<!--     </dt>> -->
<!--     <dd class='wp-caption-text gallery-caption'>> -->
<!--       <font color="#09BCE8"> J.-L. Toutant, E. Andres, T. Roussillon, Digital circles,> -->
<!-- spheres and hyperspheres: From morphological models to analytical> -->
<!-- characterizations and topological properties, Discrete Applied> -->
<!-- Mathematics, Volume 161, Issues 16–17, November 2013, Pages 2662-2677<br> </font>> -->

      

<!--   </dd></dl><br style="clear: both" />> -->
  
      
    



<!-- </div>> -->

<br>

<?php include("footer.html") ?>

